.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. rwtalers_qt test_rwtalers_qt
clean: FORCE
	$(MAKE) -C .. rwtalers_qt_clean test_rwtalers_qt_clean
check: FORCE
	$(MAKE) -C .. test_rwtalers_qt_check
rwtalers-qt rwtalers-qt.exe: FORCE
	 $(MAKE) -C .. rwtalers_qt
